# Generated by Django 5.2.9 on 2025-12-16 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid_month", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reference", models.CharField(blank=True, max_length=128, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_payments",
                        to="accounts.company",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="accounts.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_month", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "paid_month"],
                        name="accounts_pl_company_02dc88_idx",
                    )
                ],
                "unique_together": {("company", "paid_month", "reference")},
            },
        ),
    ]
