# Generated by Django 5.2.9 on 2025-12-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_planpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="clinic_limit",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_clinics",
            field=models.IntegerField(
                default=1, help_text="Máximo de clínicas permitidas"
            ),
        ),
    ]
