# Generated by Django 5.2.9 on 2025-12-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clinic",
            options={
                "ordering": ["-id"],
                "verbose_name": "Clinic",
                "verbose_name_plural": "Clinics",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["-id"],
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.AlterModelTable(
            name="clinic",
            table="clinics",
        ),
        migrations.AlterModelTable(
            name="room",
            table="rooms",
        ),
    ]
