# Generated by Django 5.2.9 on 2025-12-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("document_type", models.CharField(default="CC", max_length=20)),
                ("document_number", models.CharField(max_length=50, unique=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("phone_number", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_phone",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
