# Generated by Django 5.2.9 on 2026-01-02 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CEDULA", "Cédula"),
                            ("PASAPORTE", "Pasaporte"),
                            ("RNC", "RNC"),
                        ],
                        default="CEDULA",
                        max_length=20,
                    ),
                ),
                ("document_number", models.CharField(max_length=50, unique=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("phone_number", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "insurance_provider",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "insurance_number",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_phone",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "db_table": "patients",
                "ordering": ["-id"],
            },
        ),
    ]
