# Generated by Django 5.2.9 on 2025-12-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": ["-id"],
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.AlterModelTable(
            name="patient",
            table="patients",
        ),
    ]
