# Generated by Django 5.2.9 on 2025-12-12 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_alter_appointment_options_and_more"),
        ("notifications", "0002_alter_notification_options_alter_notification_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="Modelo")),
                (
                    "object_id",
                    models.CharField(max_length=50, verbose_name="ID del objeto"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Creación"),
                            ("UPDATE", "Actualización"),
                            ("DELETE", "Eliminación"),
                        ],
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                ("changes", models.JSONField(default=dict, verbose_name="Cambios")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de auditoría",
                "verbose_name_plural": "Registros de auditoría",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="audit_logs_created_43fcd6_idx"
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="audit_logs_model_n_656046_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="audit_logs_user_id_6193b2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TwilioLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("OUTBOUND", "Saliente"), ("INBOUND", "Entrante")],
                        max_length=10,
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "message_sid",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="SID del mensaje",
                    ),
                ),
                ("from_number", models.CharField(max_length=50, verbose_name="Desde")),
                ("to_number", models.CharField(max_length=50, verbose_name="Para")),
                ("body", models.TextField(verbose_name="Contenido")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En cola"),
                            ("sending", "Enviando"),
                            ("sent", "Enviado"),
                            ("delivered", "Entregado"),
                            ("read", "Leído"),
                            ("failed", "Fallido"),
                            ("undelivered", "No entregado"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Datos de respuesta"
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Código de error",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de error"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="twilio_logs",
                        to="appointments.appointment",
                        verbose_name="Cita",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="twilio_logs",
                        to="notifications.notification",
                        verbose_name="Notificación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Twilio",
                "verbose_name_plural": "Logs de Twilio",
                "db_table": "twilio_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="twilio_logs_created_cb7ad3_idx"
                    ),
                    models.Index(
                        fields=["status"], name="twilio_logs_status_395740_idx"
                    ),
                    models.Index(
                        fields=["direction", "-created_at"],
                        name="twilio_logs_directi_615532_idx",
                    ),
                ],
            },
        ),
    ]
