# Generated by Django 5.2.9 on 2025-12-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={
                "ordering": ["-id"],
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
            },
        ),
        migrations.AlterModelTable(
            name="doctor",
            table="doctors",
        ),
    ]
