# Generated by Django 5.2.9 on 2025-12-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "ordering": ["-id"],
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
            },
        ),
        migrations.AlterModelOptions(
            name="appointmentaction",
            options={
                "ordering": ["-id"],
                "verbose_name": "AppointmentAction",
                "verbose_name_plural": "AppointmentActions",
            },
        ),
        migrations.AlterModelTable(
            name="appointment",
            table="appointments",
        ),
        migrations.AlterModelTable(
            name="appointmentaction",
            table="appointmentActions",
        ),
    ]
