# Generated by Django 5.2.9 on 2025-12-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "ordering": ["-id"],
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
            },
        ),
        migrations.AlterModelTable(
            name="schedule",
            table="schedules",
        ),
    ]
