"""PDF chord chart generator using ReportLab."""

import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    HRFlowable,
    Table,
    TableStyle,
)


def generate_pdf(
    chord_chart_text: str,
    song_title: str,
    uploader: str,
    bpm: float,
    output_dir: str,
) -> str:
    """
    Generate a styled PDF chord chart.

    Returns the absolute path to chords.pdf.
    """
    pdf_path = os.path.join(output_dir, "chords.pdf")
    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ChartTitle",
        parent=styles["Title"],
        fontSize=22,
        leading=28,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=4,
    )

    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#4a4e69"),
        spaceAfter=2,
    )

    section_style = ParagraphStyle(
        "Section",
        parent=styles["Heading2"],
        fontSize=13,
        textColor=colors.HexColor("#e94560"),
        spaceBefore=14,
        spaceAfter=4,
    )

    chord_style = ParagraphStyle(
        "Chord",
        parent=styles["Code"],
        fontSize=11,
        leading=18,
        textColor=colors.HexColor("#1a1a2e"),
        fontName="Courier",
        spaceAfter=2,
    )

    meta_style = ParagraphStyle(
        "Meta",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#888888"),
    )

    story = []

    # Header
    story.append(Paragraph(song_title, title_style))
    if uploader:
        story.append(Paragraph(f"Artist / Channel: {uploader}", subtitle_style))
    story.append(Paragraph(f"Tempo: <b>{bpm} BPM</b>", subtitle_style))
    story.append(Spacer(1, 0.3 * cm))
    story.append(
        HRFlowable(width="100%", thickness=2, color=colors.HexColor("#e94560"))
    )
    story.append(Spacer(1, 0.5 * cm))

    # Chord chart body
    current_section = None
    buffer_lines: list[str] = []

    def flush_buffer():
        if buffer_lines:
            joined = "\n".join(buffer_lines)
            story.append(Paragraph(joined.replace("\n", "<br/>"), chord_style))
            buffer_lines.clear()

    for raw_line in chord_chart_text.splitlines():
        line = raw_line.strip()
        if not line:
            flush_buffer()
            story.append(Spacer(1, 0.2 * cm))
            continue

        # Detect section headers (words like Intro, Verse, Chorus, Bridge, Outro)
        upper = line.upper()
        section_keywords = ("INTRO", "VERSE", "CHORUS", "BRIDGE", "OUTRO", "PRE-", "SOLO", "INTERLUDE")
        if any(upper.startswith(kw) for kw in section_keywords) or (
            line.endswith(":") and len(line) < 30
        ):
            flush_buffer()
            if current_section != line:
                current_section = line
                story.append(Paragraph(line.rstrip(":"), section_style))
            continue

        # Skip repeat of title/tempo (already in header)
        if "CHORD CHART" in upper or "TEMPO:" in upper:
            continue

        buffer_lines.append(line)

    flush_buffer()

    # Footer
    story.append(Spacer(1, 1 * cm))
    story.append(
        HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc"))
    )
    story.append(Spacer(1, 0.2 * cm))
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    story.append(
        Paragraph(
            f"Generated by YouTube Multitrack · {generated_at}",
            meta_style,
        )
    )

    doc.build(story)
    return pdf_path
