# Generated by Django 5.2.9 on 2025-12-12 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(default="whatsapp", max_length=20)),
                ("to", models.CharField(max_length=50)),
                ("template", models.CharField(max_length=100)),
                ("status", models.CharField(default="queued", max_length=20)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="appointments.appointment",
                    ),
                ),
            ],
        ),
    ]
